DROP TABLE IF EXISTS civilization CASCADE;
DROP TABLE IF EXISTS tech_required_tech CASCADE;
DROP TABLE IF EXISTS unit_required_tech CASCADE;
DROP TABLE IF EXISTS unit_required_unit CASCADE;
DROP TABLE IF EXISTS tech_required_unit CASCADE;
DROP TABLE IF EXISTS technology CASCADE;
DROP TABLE IF EXISTS technology CASCADE;
DROP TABLE IF EXISTS unit CASCADE;
DROP TABLE IF EXISTS help_text;
